// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZSEa4v0nI0VR3ctwO8GVfaYHo_yOz1w',
    appId: '1:356835817096:web:e092d53229f19a80c8913d',
    messagingSenderId: '356835817096',
    projectId: 'notificationdemo-f701d',
    authDomain: 'notificationdemo-f701d.firebaseapp.com',
    storageBucket: 'notificationdemo-f701d.appspot.com',
    measurementId: 'G-HMCPWEP5YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhETuI6cO6USW-4dCkBmgDMl1v1h_9tcE',
    appId: '1:356835817096:android:119525cb451546a7c8913d',
    messagingSenderId: '356835817096',
    projectId: 'notificationdemo-f701d',
    storageBucket: 'notificationdemo-f701d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVoVnf2vSf46V7nuQ8qSaTmRW_IgR_Hfg',
    appId: '1:356835817096:ios:6112c17986a29ffec8913d',
    messagingSenderId: '356835817096',
    projectId: 'notificationdemo-f701d',
    storageBucket: 'notificationdemo-f701d.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );
}
